title: My Blog post
author: Shweta Jagdhane
email: shwetajagdhane06@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my Blog!!
  
  Hey, I am Shweta.

# social links
twitter_username: shweta_jagdhane # DO NOT include the @ character, or else the build will fail!
github_username:  shw06 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
